### ISSUE TITLE
Not working in Xcode 6.2

### ISSUE THREAD

**Issue by khendry** [tyeen/BlockJump#6]
Seems to be non-functional in Xcode 6.2 installed with Alcatraz.

**Comment by tyeen** [comment]
Have you tried to restart the Xcode?
I uninstalled it from Alcatraz, then reinstalled it. At that moment, the plug-in was not loaded by Xcode.
But after a restart of Xcode, everything just became fine.

**Comment by khendry** [comment]
I had issues after my 6.2 upgrade. Removed all my plugins and Alcatraz. Everything was good once more. Then I started to re-install plugins. Many are not working or just not installing properly in 6.2 yet. I've restarted Xcode and it still is not working. I will try to uninstall and re-install just this plugin to see if that works.

**Comment by tyeen** [comment]
Well, both Xcode and Alcatraz could go insane :P
When new Xcode came, what I always do is remove all Xcode caches like files in ~/Library/Developer/Xcode.
About Alcatraz, there are some issues/PRs committed by other plug-in creators, like this one: https://github.com/supermarin/Alcatraz/pull/233
You might try to install it by the manual way to determine whether it's the issue of Alcatraz.

I'm not sure where goes wrong but I'll keep this opening to see if there is same report. By the way, any logs would be helpful.

**Comment by tyeen** [comment]
Since a new major version Xcode 7 has been released and there's no more similar report, I think it's time to close this issue.
