### ISSUE TITLE
Not working in Xcode 7.1.1

### ISSUE THREAD

**Issue by converted2mac** [tyeen/BlockJump#8]
Tested via Alcatraz and build-from-source.

Not sure that it's correctly adding a keys to the `com.apple.dt.Xcode.plist` file.

**Comment by tyeen** [comment]
It's working fine here in both 7.1.1 and 7.2 beta.
Is there a menu item called `Change BlockJump Shortcut`(usually the last item) under `Editor` which means the plug-in is loaded?
To confirm keys in `com.apple.dt.Xcode.plist`, you can print its content by:
`/usr/libexec/PlistBuddy -c "Print" ~/Library/Preferences/com.apple.dt.Xcode.plist`
The keys should appear in the last few lines.

**Comment by converted2mac** [comment]
It wasn't at the time; it is now, however. Thinking a reboot may have fix it.
