### ISSUE TITLE
"//MARK:" breaks jumping back

### ISSUE THREAD

**Issue by mr-v** [tyeen/BlockJump#9]
Hi,
first of all thanks for making navigation in Xcode a little bit easier!

Now for the bug report: when Swift code has comment with `MARK:` or `MARK: -`, jumping back doesn't work, e.g. it can't reach `abc` function in the code below. For `MARK: - some text` jumping work as expected.

``` swift
class A {
  func abc() {

  }

  // MARK:

  private func xyz() {

  }
}
```

**Comment by tyeen** [comment]
Thanks for the reporting. And apologise for replying late. I think I've encountered this problem, too. But within a busy project, I couldn't spare time to fix it. I'll look into it soon.

**Comment by tyeen** [comment]
Should be fixed now :)

**Comment by mr-v** [comment]
Great, thank you! Finally got to updating the plugin.
